town: Hardwick
state: MA
zip: "01031"
base_url: https://www.mytowngovernment.org
data_dir: Hardwick_Data
log_level: DEBUG
log_file: Hardwick_Data/scraper.log
error_log_file: Hardwick_Data/errors.log
cache:
  enabled: true
  directory: Hardwick_Data/cache
  ttl_hours: 24
screenshots:
  enabled: true
  format: [png, pdf]
  directory: screenshots
boards:
  - name: Planning_Board
    url: https://www.mytowngovernment.org/board?board=ahNzfnRvd25nb3Zlcm5tZW50LWhychILEgpCb2FyZE1vZGVsGLnYFAw
    meetings:
      - date: 2024-09-10 18:30:00
        url: https://www.mytowngovernment.org/meeting?meeting=ahNzfnRvd25nb3Zlcm5tZW50LWhychkLEgxNZWV0aW5nTW9kZWwYgIDAoeWjgwkM